import {BaseSeeder} from '@adonisjs/lucid/seeders'
import Dish from "#models/dish";

export default class extends BaseSeeder {
    async run() {
        await Dish.createMany([
            {name: 'lasagne'},
            {name: 'tiramisu'},
            {name: 'salade'},
            {name: 'semoule'},
            {name: 'légume couscous'},
            {name: 'steak haché'},
            {name: 'surgelés'},
            {name: 'velouté de choux fleur'},
            {name: 'purée'},
            {name: 'carotte'},
            {name: 'poulet'},
            {name: 'champignon'},
            {name: 'wrap saumon oeuf'},
            {name: 'salade de lentille'},
            {name: 'oeuf à la coque'},
            {name: 'pizza'},
            {name: 'tartine de concombre'},
            {name: 'smashed potatoes'},
            {name: 'jambon blanc'},
            {name: 'poulet au curry'},
            {name: 'salade de tomates'},
            {name: 'fish’n’chips'},
            {name: 'hachi parmentier'},
            {name: 'tagliatelle saumon'},
            {name: 'plateau repas'},
            {name: 'pâtes carbonara'},
            {name: 'lasagne saumon'},
            {name: 'tartine mozarella'},
            {name: 'risotto poulet'},
            {name: 'risotto aux poireaux'},
            {name: 'filet mignon'},
            {name: 'burger'},
            {name: 'frites'},
            {name: 'fajita'},
            {name: 'quesadillas aux champignons'},
            {name: 'pizza maison'},
            {name: 'röstis de pommes de terre façon croques-madame'},
            {name: 'soupe au potiron'},
            {name: 'wrap poulet'},
            {name: 'pavé de saumon au beurre persillé'},
            {name: 'tarte aux poireaux et au bacon'},
            {name: 'haricots verts'},
            {name: 'cordon bleu'},
            {name: 'panini'},
            {name: 'croque-monsieur'},
            {name: 'salade pois chiche'},
        ])
    }
}
